nama = input("siapa namamu?:")
sekolah = input ("sekolah dimana?:")
kelas = input ("kelas berapa sekarang?;")
jurusan = input ("masuk jurusan apa?:")
hobi = input ("hobi kamu apa?:")
umur = input ("umur kamu berapa?:")
makanan = input ("makanan favoritmu?:")
game = input ("game favoritmu?:")
hero = input ("hero favoritmu?:")
tim = input ("tim favorit saya?:")
print ("halo nama saya",nama , "saya sekolah di",sekolah ,"saya kelas",kelas,"dan masuk jurusan",jurusan ,"hobi saya",hobi ,"umur saya",umur ,"saya suka makan",makanan ,"saya suka bermain game",game ,"hero fav saya",hero,"tim esport kesukaan saya",tim , )